#pragma once
#include <algorithm>
#include <chrono>
#include <x86intrin.h>
#include <iomanip>
#include <iostream>
#include <locale.h>
#include <sstream>
#include <stdint.h>
#include <stdio.h>
#include <string>
#include <time.h>
#include <utility>
#include <vector>
#include <cmath>
#include <random>
#include <cstring>
#include <fstream>
using namespace std;